### ISSUE TITLE
AZ-900 Module 12 & 13 pulling down the same file.

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftLearning/Lab-Demo-Recordings#2]
Module 03 - Security, Privacy, Compliance and Trust - 12 - Secure network traffic
Module 03 - Security, Privacy, Compliance and Trust - 13 - Implement Azure Key Vault

**Comment by ilikesql** [comment]
File was missing will update

**Comment by ilikesql** [comment]
Thanks for reporting, this is now fixed
