### ISSUE TITLE
Contribute videos

### ISSUE THREAD

**Issue by sangramrath** [MicrosoftLearning/Lab-Demo-Recordings#3]
@ilikesql can I contribute to creating the videos? (I am an MCT and deliver many of these trainings)

**Comment by ilikesql** [comment]
@sangramrath - absolutely - you are more than welcome to email me!

**Comment by bzalewa** [comment]
I can also hep(I am an MCT and deliver many of these trainings)

**Comment by ilikesql** [comment]
Thanks for the comments, we are currently evaluating and will discuss it as part of MCT program and comms
